repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright
        entry: ./server/.venv/Scripts/basedpyright.exe
        args: ["--project", "server"]
        language: system
        pass_filenames: false
        types: [python]
